# Generated by Django 4.0.6 on 2022-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='c_item',
            field=models.IntegerField(default=1),
        ),
    ]
